### PR TITLE
Add missing iterator

### PR DESCRIPTION
**Pull request by Ragoon35**
I had a compilation problem under visual 2010 ... it seems that there is a missing increment of an iterator while listing presentation picture list.

### CODE REVIEW

**Comment by mofo7777** [comment]
Are you sure ?

++it is done when else, and erase return correct it, because of erase.

Increment is not missing, it is just well handled.

The ";" is just missing.

`void CDxva2Decoder::ErasePastFrames(const LONGLONG llTime){

	for(deque<PICTURE_PRESENTATION>::const_iterator it = m_dqPicturePresentation.begin(); it != m_dqPicturePresentation.end();){

		if(it->llTime <= llTime)
			it = m_dqPicturePresentation.erase(it);
		else
			++it;
	}
}
`

**Comment by Ragoon35** [comment]
Ok, my mistake but you should add a ; in the for condition to be compatible with VS2010. 
for(deque<PICTURE_PRESENTATION>::const_iterator it = m_dqPicturePresentation.begin(); it != m_dqPicturePresentation.end() ; ){ 

Thanks 


De: "mofo7777" <notifications@github.com> 
À: "mofo7777/H264Dxva2Decoder" <H264Dxva2Decoder@noreply.github.com> 
Cc: "David Pesce" <david.pesce@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Samedi 25 Juillet 2020 05:11:23 
Objet: Re: [mofo7777/H264Dxva2Decoder] Add missing iterator (#2) 





Are you sure ? 

++it is done when else, and erase return correct it, because of erase.

**Comment by mofo7777** [comment]
Can you update your pull request ?

**Comment by Ragoon35** [comment]
Update done. Thanks!

**Pull request merged**
